apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-link-bird-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: react-link-bird
  template:
    metadata:
      labels:
        app: react-link-bird
    spec:
      containers:
      - name: react-link-bird
        image: hirebarend/react-link-bird:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
          limits:
            memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: react-link-bird-service
spec:
  selector:
    app: react-link-bird
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
