apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-link-bird-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-link-bird
  template:
    metadata:
      labels:
        app: react-link-bird
    spec:
      containers:
      - name: react-link-bird
        image: hirebarend/react-link-bird:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-link-bird-service
spec:
  selector:
    app: react-link-bird
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
